#Counts Number of Zeroes And Ones in a Binary Number	
  AREA BZO,CODE,READONLY
NUM RN 1
NONE RN 2
NZERO RN 3
ENTRY	LDR NUM,=0xB
		MOV NONE,#0
		MOV NZERO,#0
		MOV R5,#0X40000000
LOOP LSRS NUM,#1
	 ADDCS NONE,#1
	 ADDCC NZERO,#1
	 CMP NUM,#0
	 BNE LOOP
	 STR NONE,[R5]
	 STR NZERO,[R5,#4]
GO B GO 
	END
	 
